# -*- coding: utf-8 -*-
"""google collab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsmbnXQ1UqyY6a-viq1gekaoglDG6c_1
"""

print("Hello Data Science from Colab")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

print("All libraries are working in Colab too!")

